@env = dev

### Autenticação - Login
POST {{HOST}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "novo@example.com",
  "password": "P@ssw0rd!"
}


### Usar Token Para Consultas
# As requisições abaixo vão executar somente após o login gerar TOKEN

### Listar Usuários
GET {{HOST}}/api/users HTTP/1.1
Authorization: Bearer {{TOKEN}}

### Obter Usuário por ID
GET {{HOST}}/api/users/{{USER_ID}} HTTP/1.1
Authorization: Bearer {{TOKEN}}

### Listar Jogos
GET {{HOST}}/api/games HTTP/1.1
Authorization: Bearer {{TOKEN}}

### Obter Jogo por ID
GET {{HOST}}/api/games/{{GAME_ID}} HTTP/1.1
Authorization: Bearer {{TOKEN}}

### Criar Usuário (Admin)
POST {{HOST}}/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Novo Usuário",
  "email": "novo@example.com",
  "password": "P@ssw0rd!",
  "role": "Administrator"
}

### Criar Jogo (Admin)
POST {{HOST}}/api/games HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Novo Jogo"
}

### Atualizar Usuário (Admin)
PUT {{HOST}}/api/users/{{USER_ID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Usuário Atualizado"
}

### Atualizar Jogo (Admin)
PUT {{HOST}}/api/games/{{GAME_ID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Jogo Atualizado"
}

### Deletar Usuário (Admin)
DELETE {{HOST}}/api/users/{{USER_ID}} HTTP/1.1
Authorization: Bearer {{TOKEN}}

### Deletar Jogo (Admin)
DELETE {{HOST}}/api/games/{{GAME_ID}} HTTP/1.1
Authorization: Bearer {{TOKEN}}